### ISSUE TITLE
Collection of functions & libs v one big stdlib

### ISSUE THREAD

**Issue by hi5** [ahkscript/libcrypt.ahk#1]
Should this repo become a collection of individual functions and libraries OR should all crypting functions be included into one bigger stdlib compatible library?

Base64.ahk
Rot13.ahk
etc

vs

LC_Base64_*
LC_Rot13
etc

**Comment by joedf** [comment]
Good question, Both options are fine, but i would personally go With 
`LC_Func()`

**Comment by G33kDude** [comment]
The way git is designed makes single-file projects hard to collaborate on. I'm not sure if it'd work, but what if we do separate files each using the LC_ prefix, but then have a LC.ahk file that #includes all the others. Would AHK's auto-include work with that? If it doesn't, it'd be trivial to write a script to just stick all the other files together.

**Comment by joedf** [comment]
Good point, in that case, Ill go with that.

**Comment by maestrith** [comment]
What sort of projects are you guys looking for?

**Comment by joedf** [comment]
An encoding/crypting ahk lib to end all such lib! O__O 
Well, more precisely, we're aiming a StdLib type of lib. 
I.e. following the ASPDM guidelines :
https://github.com/ahkscript/ASPDM/blob/master/Specifications/Guidelines.md

**Comment by maestrith** [comment]
Ah, well I am out then.  The only encryption I use is Crypt32.dll\CryptBinaryToString for debugging in Studio.  I really have no use for encryption.

**Comment by joedf** [comment]
Encryption AND ENCODING :P

**Comment by maestrith** [comment]
My one encryption/decryption set of functions is in Studio.  I can post it if you like but it just does 1 thing.

**Comment by joedf** [comment]
All contributions are welcome. :+1:
