### ISSUE TITLE
install.ahk

### ISSUE THREAD

**Issue by G33kDude** [ahkscript/libcrypt.ahk#12]
Would anybody mind if I made a script "install.ahk" in the root that automatically copied the latest build to `%A_WorkingDir%\AutoHotkey\lib`? And if I do make an installer, should it automatically run make before copying?

**Comment by joedf** [comment]
Good idea! It would be nice to have the autohotkey installer style too! :+1:
We could also add in a logo for fun.

**Comment by G33kDude** [comment]
Well, in theory this is supposed to be similar to Gnu make. I guess I might just modify make to allow a parameter "install" so you open up cmd and run

```
make.ahk
make.ahk install
```

However, that'd require you to open the command prompt

**Comment by joedf** [comment]
Yes, but that's a cool idea too ;)
It's up to you! Unless anybody else has something to say?

**Comment by G33kDude** [comment]
Another opinion or two would be great. If I do make one, I'm not sure an elaborate GUI would be a good idea. Maybe it'd be better to do both? `make.ahk install` for the non-gui installer, and `install.ahk` for the GUI one.

As for the GUI, nothing too elaborate should be necessary, since large amounts of code for a simple task isn't usually what I aim for. If I make the GUI, it'd probably just be some text and a few buttons (e.g. one for Program Files, one for MyDocuments, etc). I might throw in a checkbox for "recompile" so it'll re-make it instead of just copying the last build.

make.ahk would be changed to allow `install`, `remove/uninstall` and `C:\Path\To\Install\name.ext` I think. If you use the default install/uninstall, it'll do the docs folder. If you specify a path, it'll overwrite whatever is there with the new version.

**Comment by joedf** [comment]
No a problem, A simple GUI with make install is fine. We can change something, if we don't like it.

**Comment by G33kDude** [comment]
I guess that's true. I'll start work on it

**Comment by hi5** [comment]
How about making it a https://github.com/ahkscript/ASPDM package instead :question:

**Comment by G33kDude** [comment]
I'm not entirely sure how package making works, and supposing we did make it a package that'd require someone to build the package and update it on a repository somewhere. I suppose that could be automated, but we might want to be pretty stable before we put that effort in

**Comment by joedf** [comment]
oh, well it's pretty easy actually! ;)
Works pretty much like git, Just use the package builder, and voila ;)
.asdpm_ignore is like .gitignore
