### ISSUE TITLE
Version hasn't been being bumped when features were added.

### ISSUE THREAD

**Issue by G33kDude** [ahkscript/libcrypt.ahk#13]

**Comment by joedf** [comment]
I lost count. :P
How about `0.0.17.21` ?
0 : not stable/full yet
0 : dido
17 : as in 17 working algorithms
21 : approx. number of "sub"-commits for the 17 algorithms

**Comment by G33kDude** [comment]
¯_(ツ)_/¯ sounds fine to me

**Comment by hi5** [comment]
How about moving code that is not fully working yet ((x)tea, ascii85?) to /src-dev/ and only keep properly working funcs in /src/ that way experiments in /src-dev/ don't require a bump in the version number. :question:

**Comment by joedf** [comment]
@G33kDude hahha, Alright great :+1: 
@hi5  hmm good point

**Comment by G33kDude** [comment]
> "version bumb"

Anyways, branches are cheap. Maybe I should work on the installer in a separate branch as well?

**Comment by joedf** [comment]
Hmmm... I don't know... What do you think @hi5 ?

**Comment by hi5** [comment]
I don't mind if it is developed in the main branch - I **haven't tried** it yet but evilC has an installer script which may be of use https://github.com/evilC/AHK-Library-Setup

**Comment by G33kDude** [comment]
Although that looks well thought out, the "put a placeholder #Include script in ProgFiles" is something I'd rather avoid for two reasons. The first is that it'd require administrator (which can be alleviated by putting it into the MyDocs folder), and the second is that it'd require the person to keep their copy of the library in the same spot all the time. This isn't an issue for people who clone repos into a central directory and leave it there, but that's not the average AHK user, I think.

That being said, it made me realize one of the advantages of having a template. That is, when there's a template you can just #Include said template and use the changes live as they happen (without first requiring it to be built again). I think that make.ahk might want to also output a template to the build directory, for this purpose.

---

We should consider opening another issue for further discussion.
