### ISSUE TITLE
VxE Encryption

### ISSUE THREAD

**Issue by jNizM** [ahkscript/libcrypt.ahk#16]
As I see you add custom Encryption like nnnik's one, ask VxE to add this function
http://www.autohotkey.com/board/topic/56223-vxes-encryption-second-gen/

**Comment by joedf** [comment]
Thanks

**Comment by joedf** [comment]
**commit:** https://github.com/ahkscript/libcrypt.ahk/commit/a97fffb2fd241ce5370bb6ec5aa6af9f0314a39d
