### ISSUE TITLE
Differentiate between Hashing & Encryption

### ISSUE THREAD

**Issue by hi5** [ahkscript/libcrypt.ahk#23]
Perhaps it would be useful to split the **functions**<sup>[1](https://github.com/ahkscript/libcrypt.ahk#functions-wip)</sup> in the readme into:
1. Hash functions - https://en.wikipedia.org/wiki/List_of_hash_functions and 
2. Encryption functions - https://en.wikipedia.org/wiki/Encryption

**Comment by jNizM** [comment]
Hashing:
- CRC32
- MD2, MD4, MD5
- SHA-1
- SHA-2 (SHA-256, SHA-384, SHA-512)
- HMAC (Checksums)
- Secure Salted (Checksums)
- Tiger
- Whirlpool

Hashing (Custom):
- Laszlo Hash (L64, L128)

En-/Decryption:
- 3DES
- AES
- Blowfish
- Caesar Cipher
- RC2, RC4
- TEA (xxTEA)
- Vigenère Cipher
- XOR

En-/Decryption (Custom):
- nnnik21
- VxE (VxE-89, VxE-251)

**Comment by joedf** [comment]
Thanks, :+1: 
sorry crazy busy this week :P
