### ISSUE TITLE
RC4 via WinAPI?

### ISSUE THREAD

**Issue by mmikeww** [ahkscript/libcrypt.ahk#28]
Anyone know where I can find an RC4 algo using the WinCryptoApi? I'm currently using Laszlo's which looks similar to [the one in this repo](https://github.com/ahkscript/libcrypt.ahk/blob/master/src/RC4.ahk). But both are dependent upon SetFormat which is removed in AHK v2. So I'm hoping for a quick link to an algo using the win api but still encrypts to hex...

**Comment by hi5** [comment]
[jNizM's Encrypt & Decrypt Text tweaked](https://autohotkey.com/boards/viewtopic.php?t=5838):

HASH and Encryption algorithms currently available:
HashAlg IDs:
1 - MD5
2 - MD2
3 - SHA
4 - SHA_256	;Vista+ only
5 - SHA_384	;Vista+ only
6 - SHA_512	;Vista+ only

CryptAlg and hmac_alg IDs:
1 - RC4
2 - RC2
3 - 3DES
4 - 3DES_112
5 - AES_128 ;not supported for win 2000
6 - AES_192 ;not supported for win 2000
7 - AES_256 ;not supported for win 2000

❔

**Comment by mmikeww** [comment]
Thanks. That actually looks like the library by Deo not jNizM. In any case, I can't seem to get the same encryption results as the other RC4 algo in here. Do you know how I can make it compatible? I'll have to play around more.

**Comment by mmikeww** [comment]
I'm guessing [`LC_RC4_Encrypt`](https://github.com/ahkscript/libcrypt.ahk/blob/master/src/RC4.ahk) isn't hashing the pw first? I'm too stupid to figure this out
