### ISSUE TITLE
Function usage document as comments

### ISSUE THREAD

**Issue by joedf** [ahkscript/libcrypt.ahk#3]
The function usage should have a standard format of documentation as a short comment over each function in its lib file.

Suggested format:

```
Description : [tab] ...
Usage : [tab] param1 - the input string to be ...
[tab] [tab?] param2 - ...
```

Thoughts?

**Comment by G33kDude** [comment]
What about the GenDocs project? Perhaps we should consider following its format?

**Comment by joedf** [comment]
Perfect.
