### ISSUE TITLE
FIX: LC_UrlEncode differs from JavaScript implementation

### ISSUE THREAD

**Issue by anonymous1184** [ahkscript/libcrypt.ahk#30]
Not a big deal, just differs from the standard (in my case caused a little conflict). RegEx parameter should be `[!#$&-;=?-Z_a-z~]` in
https://github.com/ahkscript/libcrypt.ahk/blob/2558ea686a713fe468031c0a0385ec89c63e763e/src/URI.ahk#L26

Rationale:

In [ascii-code.com](https://www.ascii-code.com/) a more visual representation is found, however getting a list of all the non-control ASCII chars:
```
i := 33, s :=
While (i < 127)
    s .= Chr(i++)
/* Result:
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
*/
```

And in a JavaScript console:
```
// Escaped: Single quote and Backslash
uri = '!"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~';
enc = encodeURI(uri);
dec = decodeURI(enc);
console.log(enc)
console.log(dec)
```
Removing the encoded chars leaves the list provided as RegEx. Hope it helps someone.

**Comment by joedf** [comment]
For reference: the difference between `enc` and `dec` in the javascript version is `` "%<>[\]^`{|} ``. The `[!#$&-;=?-Z_a-z~]` selector seems catch a few more characters than `[0-9a-zA-Z:/;?@,&=+$#.]`. I'm sure how much we want selected here because of the comment right before: `; keep ":/;?@,&=+$#."`...

@G33kDude can you take a look?

**Comment by anonymous1184** [comment]
The RegEx provides compatible match for JavaScript function:

https://www.regextester.com/?fam=113443

**Comment by joedf** [comment]
Just ran the URI.ahk testcode:
`http://example.com/pages/links%28stuff%29/script%28s%29.php?var=s%20p%20a%20c%20e%20s%20%21&var2=3+5#ref`
becomes
`http://example.com/pages/links(stuff)/script(s).php?var=s%20p%20a%20c%20e%20s%20!&var2=3+5#ref`
which seems to be correct.

I've made a commit 👍 
https://github.com/ahkscript/libcrypt.ahk/commit/1f6720ef58800a7dcd348f43a10baf8913bcfde3
