### ISSUE TITLE
XOR - now broken

### ISSUE THREAD

**Issue by joedf** [ahkscript/libcrypt.ahk#5]
@nnnik Your version seems to be more efficient but, the decryption is now broken .... :(
Please try out the example : https://github.com/ahkscript/libcrypt.ahk/blob/master/examples/XOR.ahk

**Comment by nnnik** [comment]
I will look into this

**Comment by nnnik** [comment]
Fixed it.

**Comment by joedf** [comment]
Minor, but great :+1:
